### ISSUE TITLE
To start scraping docs.github.com

### ISSUE THREAD

**Issue by dominguezcelada** [octokit/webhooks#126]
https://developer.github.com/webhooks/event-payloads/ is no more

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/39992/86278971-188f0e00-bb8e-11ea-8a92-584edcfefd85.png">

We must update our scraper to get its data from https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads instead.

_Originally posted by @gr2m in https://github.com/octokit/webhooks/pull/124#issuecomment-652579313_

**Comment by gr2m** [comment]
Would you like to work on this?

**Comment by dominguezcelada** [comment]
> Would you like to work on this?

Yes! Let me draft a PR on this! :)

**Comment by gr2m** [comment]
As part of the PR, make sure to re-enable the cron schedule trigger:
https://github.com/octokit/webhooks/blob/e8a5524415ea229b06182a4f6f4a6c7215e3b25c/.github/workflows/update.yml#L2-L4
