### ISSUE TITLE
Wrong installation_repositories type definition

### ISSUE THREAD

**Issue by brunolemos** [octokit/webhooks#14]
https://github.com/octokit/webhooks.js/issues/59

```diff
  type WebhookPayloadInstallationRepositories =
-    | Array<WebhookPayloadInstallationRepositoriesItem>
-    | {
+      {
        action: string;
        installation: WebhookPayloadInstallationRepositoriesInstallation;
        repository_selection: string;
-       repositories_added: Array<any>;
+       repositories_added: Array<WebhookPayloadInstallationRepositoriesRepositoriesAddedItem>;
        repositories_removed: Array<WebhookPayloadInstallationRepositoriesRepositoriesRemovedItem>;
        sender: WebhookPayloadInstallationRepositoriesSender;
      };
```

**Comment by gr2m** [comment]
@brunolemos this repository does not have any type definitions, only a JSON representation of what you see at https://developer.github.com/v3/activity/events/types/ 

I think octokit/webhooks.js#59 would be the better place to discuss?

**Comment by wolfy1339** [comment]
Unfortunately, the `repositories_added` property can't be more explicit than that. It's a limitation, if it's not in the docs, it's not properly typed.

As for the rest of the diff, as @gr2m said, this discussion should probably be moved to 
https://github.com/octokit/webhooks.js/issues/59
