### ISSUE TITLE
🐛 Bug: Wrong folder name for ISSUE_TEMPLATEs

### ISSUE THREAD

**Issue by dominguezcelada** [octokit/webhooks#196]
**What happened?**
When trying to create a new issue, the issue template selector is not appearing

**What did you expect to happen?**
To be able to select an Issue Template

**What the problem might be**
~`.github/ISSUE_TEMPLATES/`~ ➡️ `.github/ISSUE_TEMPLATE/`

**Comment by gr2m** [comment]
resolved via https://github.com/octokit/webhooks/pull/197
