### ISSUE TITLE
Use GitHub's OpenAPI spec as source of truth for generating schemas

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks#266]
The [openapi spec](https://github.com/github/rest-api-description) for the rest api shares a lot of properties with these shemas.
Later on, we could try and use it as the source of truth where possible.

_Originally posted by @wolfy1339 in https://github.com/octokit/webhooks/issues/264#issuecomment-759701042_

**Comment by gr2m** [comment]
Is this still relevant? @wolfy1339

**Comment by wolfy1339** [comment]
It still is relevant, but I don't think we need an issue for it.

We can worry about this whenever GitHub decides to publish schemas for Webhooks themselves along with the OpenAPI spec
