### ISSUE TITLE
Include webhook event descriptions

### ISSUE THREAD

**Issue by JasonEtco** [octokit/webhooks#28]
Followup from https://github.com/octokit/webhooks.js/issues/86, it'd be really cool to include webhook event descriptions:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10660468/59793120-c5f4f380-92a3-11e9-88f3-406ca23992a8.png">

So the block of text below **OrgBlockEvent** in this example. Those can vary pretty widely, here's a different example of the same text:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/10660468/59793183-e9b83980-92a3-11e9-991e-8264d571cc5c.png">

---

**Why:**

I'd love to use this to build automatic documentation for specific features of my application, and for something where you can _choose_ an event it'd be great to share this context there. Certainly not a deal-breaker, but might be nice to have!

**Comment by zeke** [comment]
Resolved by https://github.com/octokit/webhooks/pull/98 ⚡
