### ISSUE TITLE
Typescript IssueCommentEvent.issue type is never

### ISSUE THREAD

**Issue by danielpza** [octokit/webhooks#395]
Trying to use type `IssueCommentEvent` accessing `issue` property yields `never` type:

```ts
import('@octokit/webhooks-definitions/schema').IssueCommentEvent['issue']
```

![image](https://user-images.githubusercontent.com/17787042/109697221-efc77a00-7b5b-11eb-9188-76c547706de7.png)

I would expect it to have some type, either Issue or some augmentation of it

Perhaps there's some conflict between the `Issue` type and specific type overwriting it it

**Comment by G-Rath** [comment]
That type doesn't resolve to `never`:

![image](https://user-images.githubusercontent.com/3151613/109700394-8c3e5a80-7bf6-11eb-8808-817fb14970ac.png)

![image](https://user-images.githubusercontent.com/3151613/109699884-f60a3480-7bf5-11eb-9fa9-9244d37b20b9.png)

Could you provide some more information about your setup, such as your IDE and package versions?

**Comment by danielpza** [comment]
I'm using emacs with lsp-mode, but I got a similar error using the cli:

```
$ cat test-issue-type.ts 
type Issue = import('@octokit/webhooks-definitions/schema').IssueCommentEvent['issue'];

const a: Issue = {};

$ tsc --version
Version 4.1.3

$ tsc --noEmit test-issue-type.ts 
test-issue-type.ts:3:7 - error TS2322: Type '{}' is not assignable to type 'never'.

3 const a: Issue = {};
        ~


Found 1 error.
```

**Comment by G-Rath** [comment]
What does your `tsconfig` look like?

Could you also confirm if this happens if you use an static import? (i.e `import { IssueCommentEvent } from ''@octokit/webhooks-definitions/schema"`).

**Comment by danielpza** [comment]
Yes it happens using static imports

> What does your tsconfig look like?

yep, looking at the tsconfig I found I had disabled the strict flag, enabling it fixes the issue, no other relevant modification were done to the tsconfig:

```
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "checkJs": true,                       /* Report errors in .js files. */

    /* Strict Type-Checking Options */
    "strict": false,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */

    /* Advanced Options */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

To be clear changing to `strict: true` shows the correct type.

**Comment by G-Rath** [comment]
Interesting, it's because of `strictNullChecks` - it seems that it doesn't like the fact that `closed_at` is `null` so somehow the type becomes type `never`.

Maybe it's because when that flag is false `null` is effectively removed, so it's seeing it as `never` instead? 🤔 

Sadly there's not really a lot we can do as the type is correct and valid.
You might have luck over at the TypeScript repo getting this classed as a bug.

**Comment by danielpza** [comment]
I think I'm ok with enabling `strictNullChecks`, thanks for the help
