### ISSUE TITLE
Problems with "extending" schemas in generated types

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#398]
I stumbled onto this while working on resolving https://github.com/octokit/app.js/issues/212
This should be easily reproduced, just use the type as one would normally do and TypeScript will reduce the type to `never`
```
Property 'number' does not exist on type 'never'.
  The intersection 'Issue & { state: "open"; closed_at: null; }' was reduced to 'never' because property 'closed_at' has conflicting types in some constituents.ts(2339)
```

**Comment by G-Rath** [comment]
I'm guessing you've got `strictNullChecks` off - see https://github.com/octokit/webhooks/issues/395

**Comment by wolfy1339** [comment]
Ok. Well that's ackward :sweat_smile:...

Is this documented anywhere?

**Comment by wolfy1339** [comment]
That doesn't seem to fix it for me in VSCode. I added it to `tsconfig.json`, restarted the TS server and no change. I set VSCode to use the local TS install from the project
In the tests it seems to be fine though
