### ISSUE TITLE
Make RepositoryDispatchOnDemandTestEvent  generic

### ISSUE THREAD

**Issue by tonyhallett** [octokit/webhooks#415]
https://github.com/octokit/webhooks/blob/6d075cf294414a54aa468ebe0d9763666b4f2529/schema.d.ts#L215

```
export interface RepositoryDispatchOnDemandTestEvent {
  action: "on-demand-test";
  branch: string;
  client_payload: {
    [k: string]: unknown;
  };
  repository: Repository;
  sender: User;
  installation: InstallationLite;
  organization?: Organization;
}
```

change to
```
export interface RepositoryDispatchOnDemandTestEvent<
  TClientPayload extends {
    [k: string]: unknown
  }
> {
  action: "on-demand-test";
  branch: string;
  repository: Repository;
  sender: User;
  installation: InstallationLite;
  organization?: Organization;
  client_payload: TClientPayload
}
```

**Comment by wolfy1339** [comment]
That is a good idea, however, the types are auto-generated from JSON Schemas, therefore we cannot use generics (to my knowledge)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Tony Hallett ***@***.***>
Sent: Tuesday, March 23, 2021 10:52:29 AM
To: octokit/webhooks ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [octokit/webhooks] Make RepositoryDispatchOnDemandTestEvent generic (#415)


https://github.com/octokit/webhooks/blob/6d075cf294414a54aa468ebe0d9763666b4f2529/schema.d.ts#L215

export interface RepositoryDispatchOnDemandTestEvent {
  action: "on-demand-test";
  branch: string;
  client_payload: {
    [k: string]: unknown;
  };
  repository: Repository;
  sender: User;
  installation: InstallationLite;
  organization?: Organization;
}


change to

export interface RepositoryDispatchOnDemandTestEvent<
  TClientPayload extends {
    [k: string]: unknown
  }
> {
  action: "on-demand-test";
  branch: string;
  repository: Repository;
  sender: User;
  installation: InstallationLite;
  organization?: Organization;
  client_payload: TClientPayload
}
