### ISSUE TITLE
deprecate `@octokit/webhooks-definitions`

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#444]
Maybe we could add a section "Upgrade from `@octokit/webhooks-definitions` to the README for some time`? Alternatively we could create an issue and link to that instead

_Originally posted by @gr2m in https://github.com/octokit/webhooks/pull/436#issuecomment-822071695_

**Comment by gr2m** [comment]
done, thanks.

I linked to this issue in the deprecation message. We can edit it to make it more useful:
https://github.com/octokit/webhooks/issues/447
