### ISSUE TITLE
Add all event actions to `EventPayloadMap`

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#461]
**What’s missing?**

Instead of relying just on TS inference, all event actions should be added to `EventPayloadMap`

**Why?**

As I'm in the process of upgrading the version of `@octokit/webhooks` that Probot uses, and it's `Context` class uses the `implements EmitterWebhookEvent<E extends EmitterWebhookEventName>` syntax, and you can only implement an object type or intersection of object types with statically known members.

In `@octokit/webhooks` there is the type inference when your event name includes the action (ex: `check_run.created`) in the `EmitterWebhookEvent` type which uses the `EventPayloadMap` from this package. It would allow to simplify the type in `@octokit/webhooks` and be possible to use it in class implementations

**Alternatives you tried**

No real alternatives available.

**Comment by G-Rath** [comment]
The whole point of `EventPayloadMap` is that it holds mappings to *actual* event names, which `<event>.<action>` is not, so it would be a false representation to change that; it would also be undoing most of the work I did to get us away from having that map in favor of this more accurate one, and introduce complexity in other applications which'd be directly inverse to the simplification you'd get in other packages (in fact it'd probably be more complex, as it's harder to extract than it is to compute).

Could you provide a code snippet of the error you're getting?

**Comment by wolfy1339** [comment]
This is the error message I'm getting
`A class can only implement an object type or intersection of object types with statically known members.`

This is how the class is defined:

```ts
class Context<E extends EmitterWebhookEventName = EmitterWebhookEventName> implements WebhookEvent<E> {}
```

**Comment by wolfy1339** [comment]
Using the old types they would pass through the payload with the transformation to `WebhookEvent`, and the class would be defined like this
```ts
class Context<E extends WebhookPayloadWithRepository = any> implements WebhookEvent<E> {
  public name: WebhookEvents;
  public id: string;
  public payload: E;

  public octokit: InstanceType<typeof ProbotOctokit>;
  public log: DeprecatedLogger;
}
```

**Comment by G-Rath** [comment]
Where is `WebhookEvent` coming from? Our `WebhookEvent` isn't generic, and I can't find a reference it anywhere else.

Even better would be if you had a branch or repo I could look at :)

**Comment by wolfy1339** [comment]
Oh, it's `EmitterWebhookEvent`, I just imported it as `WebhookEvent`

This is the PR I'm working on: https://github.com/probot/probot/pull/1481

Though I just restarted it locally, with a fresh slate, and this is the current iteration: https://github.com/wolfy1339/probot/tree/update-octokit-webhooks

**Comment by G-Rath** [comment]
Cheers, I'll have a look when I have the time.

I think based on the size of the app, and the use of generics you're going to have to live with some pain no matter which way you slice it; if you're wanting to get this landed, I can try and make some time to help - I can even do a call if that'd be useful.
