### ISSUE TITLE
`sender` key in webhooks

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks#510]
The `sender` key is not present e.g. in `CheckRunCreatedEvent`:
https://github.com/octokit/webhooks/blob/ced7888a863b87569035cc9b94d62a46945577b0/payload-types/schema.d.ts#L813-L917

The example for the `check_run.created` event has the `"sender"` key
https://github.com/octokit/webhooks/blob/ced7888a863b87569035cc9b94d62a46945577b0/payload-examples/api.github.com/check_run/created.payload.json#L298-L317

I'm not sure, but I'd assume a `sender` would always be present? I ran into this as I was working on https://github.com/probot/probot/pull/1559

<img width="583" alt="image" src="https://user-images.githubusercontent.com/39992/122625528-6c725b80-d05a-11eb-82b3-d336bb9474ff.png">

Do you know more about this? Happy to inquire with GitHub's Events team

**Comment by wolfy1339** [comment]
> The sender key is not present e.g. in `CheckRunCreatedEvent`

It is present for that event, I double checked. If it wouldn't be, the tests wouldn't pass, as the payload contains the sender.
The error from TS is a bit misleading, but it is correct. The `sender` property is not present in the union of ALL events

> Do you know more about this? Happy to inquire with GitHub's Events team

Here is a list of events (schema `$id`s) which do not have a sender property:
* `secret_scanning_alert$created` (Missing example payload)
* `security_advisory$performed` (Missing example payload)
* `security_advisory$published`
* `security_advisory$updated`
* `security_advisory$withdrawn`

**Comment by gr2m** [comment]
I got feedback on that: `security_advisory` does not have a sender key because there is no actor. And there are no plans at this point to a new type of actor for GitHub itself. So we will have to live with the fact that `sender` will be conditional.
