### ISSUE TITLE
refactor: use `github-enterprise-server-versions` instead of hardcoding GHES versions

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#519]
Remove hard-coded versions of GHES versions from the code in order to improve maintainability, and bring this package in line with `@octokit/openapi-types`.

Currently, we generate types for all GHES versions greater than `2.21`, and the minimum supported version of GHES is `2.22`

The versions are only hard-coded in one place in the code

https://github.com/octokit/webhooks/blob/612c853375c44912ea66c9cf8a4aaec436d9a705/lib/check-or-update-webhooks.ts#L41

**Comment by timrogers** [comment]
What is `github-enterprise-server-versions`? 😊

**Comment by wolfy1339** [comment]
It's a small npm package that @gr2m wrote that fetches the latest supported versions of GHES from the GitHub docs, and returns them for you

**Comment by wolfy1339** [comment]
As GitHub has published it's own OpenAPI spec for webhooks, efforts will be concentrated on the current community spec and transitioning to the official spec
