### ISSUE TITLE
Missing status `queued` for new added typ workflow_job

### ISSUE THREAD

**Issue by npalm** [octokit/webhooks#540]
**What happened?**
The status `queued` for the new introduced event `workflow_job` in PR #534 is missing.

**What the problem might be**

Add the thet status `queued` to the event.

**Comment by pje** [comment]
The three possible status values are `queued`, `in_progress`, `completed`.

**Comment by wolfy1339** [comment]
Thanks for the report! Would you like to send a pull request to add the missing value?

**Comment by MuIsTheTruth** [comment]
I am having trouble understanding. I am very confused and disoriented.

**Comment by wolfy1339** [comment]
@npalm Can you share a payload example with the `queued` status? I am not sure where exactly it is missing from

**Comment by npalm** [comment]
Sorry, but right now I am not able to share. I will be back in the office in 1.5 week and will share a sample.

**Comment by wolfy1339** [comment]
No problem 👍

**Comment by wolfy1339** [comment]
I think I have a payload example/schema in #558 that could close this issue. Care to take a look?
