### ISSUE TITLE
List of possible events in webhooks is not available

### ISSUE THREAD

**Issue by pawelmitka** [octokit/webhooks#550]
**What’s missing?**
There is `WebhookEventMap` type that contains mapping of events to their spec. There is also `WebhookEventName` which is a string literal type containing all possible Webhook Events that can be checked during ts compilation. However, there is no list of all available events, e.g.: as array of strings: `const WebhookEventNames=[...] as const;`

**Why?**
This is needed to provide list of available events in GUI or validate provided event in runtime.

**Alternatives you tried**

I tried to implement it in `octokit-types.ts` but I realized it only generates `schema.d.ts` which does not allow to create enums or arrays of strings.

I think, there should be an additional file containing this definition. @wolfy1339 do you have an idea how should it be implemented?

**Comment by wolfy1339** [comment]
I believe what you are looking for is already generated here: https://github.com/octokit/webhooks.js/blob/master/src/generated/webhook-names.ts

**Comment by pawelmitka** [comment]
@wolfy1339 yes, this is what I was looking for. I think, it just needs to be exported from module: https://github.com/octokit/webhooks.js/blob/6da50b0f92e8a9b619a43ced7f07c73ea64bc3df/src/index.ts#L67 Do I understand correctly?

**Comment by wolfy1339** [comment]
That's exactly it
