### ISSUE TITLE
"repository_vulnerability_alert.reopen" missing

### ISSUE THREAD

**Issue by adriandersen** [octokit/webhooks#611]
https://github.blog/changelog/2022-03-07-reopen-dismissed-dependabot-alerts/

**What’s missing?**

Webhook event for the new repository_vulnerability_alert.reopen is not yet added

**Why?**

As this functionality is now added to the dependabot webhook, it should be added here as well :)

**Comment by wolfy1339** [comment]
Thanks for the report, I will look into this
