### ISSUE TITLE
InstallationUnsuspendEvent with property "installation" with type "never"

### ISSUE THREAD

**Issue by ivancea** [octokit/webhooks#620]
**What happened?**

Using NPM package `@octokit/webhook-types`, the type InstallationUnsuspendEvent has a problem with the member `installation`, that results to `never`. Example:

```Typescript
const event = {} as InstallationUnsuspendEvent;
const installationId = event.installation.id; // Error here
```

The error:
```
Property 'id' does not exist on type 'never'.
  The intersection 'Installation & { suspended_by: null; suspended_at: null; }' was reduced to 'never' because property 'suspended_at' has conflicting types in some constituents.
```

Using TypeScript 4.5.5.

**What did you expect to happen?**

The property `installation` should be of type Installation instead of `never`.

**Comment by oscard0m** [comment]
Hi @ivancea!

Thanks for opening this issue and providing such a detailed explanation.

I tried to reproduce the issue in TS Playground but apparently, the type is properly inferred there. Am I missing something in that example to reproduce your issue?

https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAbwJIDsDOMCGAbbmbAQoCq6ArmmAKYoAmAogG40wC+cAZlBCHAEQABCAGMYEANbAYAegDuVAEYALCBLQBaGAE9qaPgG4AUIeFEMcKsxTwAvInaY0cVBhx4CRUmgrU6TFkam6PDAwW74hChItABccChkIApUUHB2liwAdKGuuBFE2bRGQA

**Comment by ivancea** [comment]
Hum, I tried a minimal example with my project config and it failed.

I'll check it on monday and try to find if there's some config or import making it fail, and comment the results here.

Thanks!

**Comment by oscard0m** [comment]
> Hum, I tried a minimal example with my project config and it failed.

Sure! Let us know the details. Also, let us know which version of `@octokit/webhook-types` are you using.

**Comment by wolfy1339** [comment]
> I tried to reproduce the issue in [this TS Playground](https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAbwJIDsDOMCGAbbmbAQoCq6ArmmAKYoAmAogG40wC+cAZlBCHAEQABCAGMYEANbAYAegDuVAEYALCBLQBaGAE9qaPgG4AUIeFEMcKsxTwAvInaY0cVBhx4CRUmgrU6TFkam6PDAwW74hChItABccChkIApUUHB2liwAdKGuuBFE2bRGQA) but apparently, the type is properly inferred there. Am I missing something in that example to reproduce your issue?

Disabling `strict` and `strictNullChecks`, I can reproduce the problem.

As seen in [this TS Playground](https://www.typescriptlang.org/play?strict=false&strictNullChecks=false&ts=4.5.5#code/JYWwDg9gTgLgBAbwJIDsDOMCGAbbmbAQoCq6ArmmAKYoAmAogG40wC+cAZlBCHAEQABCAGMYEANbAYAegDuVAEYALCBLQBaGAE9qaPgG4AUIeFEMcKsxTwAvInaY0cVBhx4CRUmgrU6TFkam6PDAwW74hChItABccChkIApUUHB2liwAdKGuuBFE2bRGQA), disabling either `strict` (which implies `strictNullChecks`), or disabling `strictNullChecks` when `strict` is disabled, the error you reported happens.

Feel free to submit a PR to improve the documentation to make this more obvious for users, and to post with other issues

**Comment by oscard0m** [comment]
> > I tried to reproduce the issue in [this TS Playground](https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAbwJIDsDOMCGAbbmbAQoCq6ArmmAKYoAmAogG40wC+cAZlBCHAEQABCAGMYEANbAYAegDuVAEYALCBLQBaGAE9qaPgG4AUIeFEMcKsxTwAvInaY0cVBhx4CRUmgrU6TFkam6PDAwW74hChItABccChkIApUUHB2liwAdKGuuBFE2bRGQA) but apparently, the type is properly inferred there. Am I missing something in that example to reproduce your issue?
> 
> Disabling `strict` and `strictNullChecks`, I can reproduce the problem.

Nice catch!
