### ISSUE TITLE
Include event source/type as a property

### ISSUE THREAD

**Issue by k2bd** [octokit/webhooks#649]
**What’s missing?**

It would be nice if the event type indicating its source was included explicitly on events themselves, for example:

```json
{
  "event_type": "issue_comment",
  "action": "created",
  "issue": {
    ...
  },
  "comment": {
    ...
  },
  "repository": {
    ...
  },
  "organization": {
    ...
  },
  "sender": {
    ...
  }
}
```

**Why?**

This would enable building an event discriminator that is both simple and robust to future extensions to the event spec.

**Alternatives you tried**

I have tried discriminating events by their structure, but this requires relying on assumptions that might not hold in future revisions of the spec. In most cases, a unique property or combination of properties can be used to distinguish events, such as 'membership' vs 'member' events, both having 'member' properties, being discriminated by the existence of a 'team' property on the former, but if any one of these assumptions among events breaks down in future, so will my discriminator.

**Comment by wolfy1339** [comment]
I don't really understand why you would need that.
The event is in the headers, and you specify which event to listen for in the handler function

**Comment by timrogers** [comment]
@k2bd Is this feedback on the webhooks that GitHub sends, or is it feedback on this project, or something else? I just want to make sure that I understand what you're looking for 😊

**Comment by k2bd** [comment]
My apologies, I missed the `X-GitHub-Event` header in the webhook spec docs, that fills my need just fine and you're right there's no need for a change in the event structure with that.

Thank you very much!
