### ISSUE TITLE
InstallationSuspendEvent installation property is typed to 'never'

### ISSUE THREAD

**Issue by bcomnes** [octokit/webhooks#707]
**What happened?**

The `InstallationSuspendEvent` is supposed to have an `installation` property but the way it is type narrowed, the property is typed to `never`. 

**What did you expect to happen?**

The `installation` property should have the `installation` property but narrowed such that `suspended_by` and `suspended_at` are `null`.

**What the problem might be**

Something having to do with the type narrowing here:

https://github.com/octokit/webhooks/blob/25f4b0a4be063a821c22af0f1d1ee5040a2e9785/payload-types/schema.d.ts#L3204-L3209

<img width="686" alt="Screen Shot 2022-09-15 at 11 15 49 AM" src="https://user-images.githubusercontent.com/166301/190468839-69f49682-900b-43fb-af85-342161b9945d.png">

For some reason TS is narrowing this to `never`.

- "typescript": "4.8.2",
- "@octokit/webhooks-types": "6.3.6",

**Comment by wolfy1339** [comment]
Can you share your `tsconfig.json`?

Cases like this is when you don't have `strict` enabled in your tsconfig

**Comment by bcomnes** [comment]
Yeah

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "strictNullChecks": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": false,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "sourceMap": true,
    "rootDir": "src",
    "outDir": "dist",
    "incremental": true,
    "tsBuildInfoFile": "./dist/tsconfig.tsbuildinfo"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "./types"
  ],
  "exclude": [
    "dist",
    ".next",
    "next.config.js",
    "node_modules",
    "experiments",
    "@chakra-ui",
    "tools",
    "submodules"
  ]
}
```

**Comment by wolfy1339** [comment]
We require that at least `strictNullChecks` be enabled
