### ISSUE TITLE
[BUG]: Remove required 'test' Check Run from repository

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks#761]
### What happened?

PR blocked by a non-existing required Check Run: `test`

Example: https://github.com/octokit/webhooks/pull/760

### Versions

not relevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Try pushing an empty commit to the branch. Sometimes GitHub gets stuck and doesn't run the checks

**Comment by oscard0m** [comment]
Closing this issue and re-opening if I see other PRs with this check
