### ISSUE TITLE
[BUG]: ProjectsV2Item and archived_at for created/converted events

### ISSUE THREAD

**Issue by edwardgronroos** [octokit/webhooks#768]
### What happened?

Using `@octokit/webhooks` in a project, and subscribing to an event.

```
  webhooks.on('projects_v2_item.created', async ({ payload }) => {
    // Not possible to subscribe to single project, so we filter
    if (payload.projects_v2_item.project_node_id === PROJECT_NODEID) {
      await boltApp.client.chat.postMessage({
        token: SLACK_BOT_TOKEN,
        channel: SLACK_CHANNEL_ID,
        text: `...`
      });
    }
  });
```

I get TS compile error:
`Property 'project_node_id' does not exist on type 'never'.
  The intersection 'ProjectsV2Item & { archived_at: null; }' was reduced to 'never' because property 'archived_at' has conflicting types in some constituents.`
  
Investigated a bit further and due to using `allOf` and `$ref` to the schema the intersection fails, since the schema states that `archived_at` can be either `string | null` and can't then be overwritten with this intersection.

### Versions

@octokit/webhooks 10.7.0
@octokit/webhooks-types 6.10.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Can you post your `tsconfig.json`?

This sounds like a case of `strictNullChecks` (or `strict` which includes the previous option) being disabled

**Comment by edwardgronroos** [comment]
You where spot on, `strict` wasn't enabled in this project 🙈
