### ISSUE TITLE
[BUG]: invalid organization format in schema for repository

### ISSUE THREAD

**Issue by evantill** [octokit/webhooks#789]
### Can not load a repository informations as a typed `Repository`

The json was loaded using `gh`: 
```shell
 gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/plantuml/plantum
```

And trying to type it as a `Repository` from `@octokit/webhooks-types` failed due to the organization data.

### Seems like the following type declaration is wrong:

https://github.com/octokit/webhooks/blob/120433d52b3acf9c33965c5324c53120d7b28dd0/payload-schemas/api.github.com/common/repository.schema.json#L429

### Versions

@octokit/webhooks-types version 6.11.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I'm not sure I understand your problem.

What exactly are you trying to do with the types?

Are you trying to receive webhook and validate them with the types?

**Comment by wolfy1339** [comment]
What you want is [`@octokit/openapi-types`](https://github.com/octokit/openapi-types.ts) for the GitHub API.

The types provided by this repository are only for webhooks

**Comment by evantill** [comment]
> I'm not sure I understand your problem.
> 
> What exactly are you trying to do with the types?
> 
> Are you trying to receive webhook and validate them with the types?

I'm writting a github workflow action in typescript and I would like to have to have a type version of the event payload.

**Comment by evantill** [comment]
> What you want is [`@octokit/openapi-types`](https://github.com/octokit/openapi-types.ts) for the GitHub API.
> 
> The types provided by this repository are only for webhooks

Thank you for you're suggestion but I'm not sure it will correspond to my actual need (see my previous comment)

**Comment by wolfy1339** [comment]
> I'm writting a github workflow action in typescript and I would like to have to have a type version of the event payload.

Using the types for other things than webhooks is not supported. There are subtle differences between Actions payloads and webhooks

**Comment by evantill** [comment]
@wolfy1339 is there other schema that I can use in action to have a typed event payload ?

**Comment by evantill** [comment]
But according to this documentation: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
the payload are described as **Webhook event payload**

I understood that  _"Not all webhook events trigger workflows."_ but the documentation reference the webhook definition: see example : https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#branch_protection_rule
