### ISSUE TITLE
[BUG]: InstallationUnsuspendEvent.installation is never

### ISSUE THREAD

**Issue by chris-feist** [octokit/webhooks#797]
### What happened?

TypeScript converts `InstallationUnsuspendEvent.installation` to type `never` because it has troubles with the union type

https://github.com/octokit/webhooks/blob/main/payload-types/schema.d.ts#L3516

I'd recommend removing the union since `suspended_by` and `suspended_at` can already be `null`. Alternatively the fields could be omitted.

```ts
  installation: Installation;
  
// or

  installation: Omit<Installation, 'suspended_by' | 'suspended_at'> & {
    suspended_by: null;
    suspended_at: null;
  };
```

### Versions

@octokit/webhooks-types: 6.11.0
typescript: 4.1.3

### Relevant log output

```shell
The intersection 'Installation & { suspended_by: null; suspended_at: null; }' was reduced to 'never' because property 'suspended_at' has conflicting types in some constituents.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Can you share your `tsconfig`?

If you don't have `strict` enabled, it resolves to `never`

**Comment by chris-feist** [comment]
I have the default setting for strict. Here is my config:
```json
// tsconfig.json
{
  "extends": "./tsconfig.paths.json",
  "compilerOptions": {
    "lib": ["ESNext"],
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "target": "ESNext",
    "outDir": "lib",
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "serverless.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

```json
// tsconfig.paths.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@functions/*": ["src/functions/*"],
      "@languages/*": ["src/languages/*"],
      "@src/*": ["src/*"],
      "@utils/*": ["src/utils/*"]
    }
  }
}
```

**Comment by wolfy1339** [comment]
At the very minimum, we require that the `strictNullChecks` be enabled.

The default value for `strict` is false (which includes `strictNullChecks`)

**Comment by chris-feist** [comment]
Is there a reason for not updating the type to support both tsconfig options?

**Comment by wolfy1339** [comment]
Even with that change, you still need `strictNullChecks` in order to use the types.

**Comment by wolfy1339** [comment]
That isn't a viable solution. The types are autogenerated from our JSON schema

**Comment by chris-feist** [comment]
Okay, makes sense then
