### ISSUE TITLE
[BUG]: Property 'title' does not exist on type 'never'.   The intersection 'Issue & { state: "open"; closed_at: null; }' was reduced to 'never' because property 'closed_at' has conflicting types in some constituents.

### ISSUE THREAD

**Issue by NeftaliYagua** [octokit/webhooks#879]
### What happened?

![Captura desde 2024-01-10 03-56-11](https://github.com/octokit/webhooks/assets/2866454/5b270ce4-43ae-4bcd-94e7-8c80ca4b37f6)
"type": ["string", "null"] VS "type": "null"

[payload-schemas/api.github.com/common/issue.schema.json:65](https://github.com/octokit/webhooks/blob/7e61eaa06955106f224b90a5eccbd1f9ecf9c721/payload-schemas/api.github.com/common/issue.schema.json#L65)

[payload-schemas/api.github.com/issues/opened.schema.json:25](https://github.com/octokit/webhooks/blob/7e61eaa06955106f224b90a5eccbd1f9ecf9c721/payload-schemas/api.github.com/issues/opened.schema.json#L25C36-L25C37)

### Versions

@octokit/rest 20.0.2,
@octokit/webhooks 12.0.11,
@octokit/webhooks-types 7.3.1
node 18.19.0

### Relevant log output

```shell
src/webhooks/webhooks.controller.ts:44:56 - error TS2339: Property 'title' does not exist on type 'never'.
  The intersection 'Issue & { state: "open"; closed_at: null; }' was reduced to 'never' because property 'closed_at' has conflicting types in some constituents.

44           `${event.sender.login} opened "${event.issue.title}" on ${event.repository.full_name}`,
                                                          ~~~~~

[3:47:56 a. m.] Found 1 error. Watching for file changes.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is an issue with your Typescript configuration.

You need to use `strictNullChecks`

https://github.com/octokit/webhooks#importing-types
