### ISSUE TITLE
scrape payloads from Github API documentation

### ISSUE THREAD

**Issue by oscard0m** [octokit/webhooks#92]
## Context
There are some examples of payloads on Github API Docs which are not matching (missing fields mostly) with the table and the real payload delivered by Github Events, so the script used in this repo to update the definitions is not covering  all of the cases.

Issues related to this topic:
https://github.com/octokit/webhooks/issues/43
https://github.com/octokit/webhooks.js/issues/87
https://github.com/octokit/webhooks.js/issues/94

## Proposal
As pointed by @gr2m [here](https://github.com/octokit/webhooks.js/issues/94#issuecomment-624317609) it would be nice to scrape the tables with each property and generate definitions from there since it seems that payloads examples are not updated with the latest changes on GitHub's

---

Let's open the discussion and clarify how to tackle it and start the development! 💪

**Comment by gr2m** [comment]
To be clear, I would not replace the current way of deriving the definitions using the examples, but I would merge the current implementation with parsing the API payload tables

**Comment by dominguezcelada** [comment]
> To be clear, I would not replace the current way of deriving the definitions using the examples, but I would merge the current implementation with parsing the API payload tables

Has sense to me

**Comment by zeke** [comment]
I plan to work on this next week.

cc @chiedo

**Comment by dominguezcelada** [comment]
> I plan to work on this next week.
> 
> cc @chiedo
> 
> Dev Effort estimate: Small

If you need assistance on that let me know :)

**Comment by zeke** [comment]
Update: I will not be working on this issue this week after all. We are initially going to migrate the https://developer.github.com/webhooks/event-payloads/ page to the help.github.com as-is, and we will revisit the effort to scrape this content into a structured format at a later date.

**Comment by gr2m** [comment]
@wolfy1339 I think we can close this issue now?

**Comment by wolfy1339** [comment]
I think so. The properties table is now parsed and included in `index.json`, and we now have the schemas
