### ISSUE TITLE
[DOCS]: Any webhook event type for repository download?

### ISSUE THREAD

**Issue by itssidhere** [octokit/webhooks#955]
### Describe the need

Hi, thanks for the awesome plugin. Can I please know if i can get the events for when someone downloads my repo for example as a zip?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
As far as I'm aware GitHub foes not provide any webhook for when someone downloads a zip of the repository.

You can request a new webhook event over here: https://github.com/orgs/community/discussions/categories/api-and-webhooks
